
const recipes = [
    {
      id: 1,
      category: "Desert",
      name: "Caramel Strawberry Milkshake",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu20.jpg",
      rating: 5,
    },
    {
      id: 2,
      category: "BreakFast",
      name: "Cashew Vegan Rice",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu21.jpg",
      rating: 4,
    },
    {
      id: 3,
      category: "BreakFast",
      name: "Omelette Supreme",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu22.jpg",
      rating: 5,
    },
    {
      id: 4,
      category: "Meal",
      name: "Salmon in Creamy Sun Dried Tomato Sauce",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu23.jpg",
      rating: 5,
    },
    {
      id: 5,
      category: "Breakfast",
      name: "Healthy Jam Waffle Breakfast",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu24.jpg",
      rating: 4,
    },
    {
      id: 6,
      category: "Desert",
      name: "Chocolate and Banana Jar Cake",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu25.jpg",
      rating: 5,
    },
    {
      id: 7,
      category: "Desert",
      name: "Caramel Blueberry Scones",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu26.jpg",
      rating: 4,
    },
    {
      id: 8,
      category: "Desert",
      name: "Blueberry Carrot Cake",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu27.jpg",
      rating: 5,
    },
    {
      id: 9,
      category: "Meal",
      name: "Vegan Cauliflower Salad",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu28.jpg",
      rating: 4,
    },
    {
      id: 10,
      category: "Meal",
      name: "Roasted Red Pepper Soup",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu29.jpg",
      rating: 5,
    },
    {
      id: 11,
      category: "Breakfast",
      name: "Eggs and Avocado Toast",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu30.jpg",
      rating: 5,
    },
    {
      id: 12,
      category: "Meal",
      name: "Pork Shoulder Cashew Noodles",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu31.jpg",
      rating: 4,
    },
    {
      id: 13,
      category: "Breakfast",
      name: "Toasted Farfalle In Pesto Sauce",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu32.jpg",
      rating: 5,
    },
    {
      id: 14,
      category: "Meal",
      name: "Cheesy Bacon Burger Sliders",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu33.jpg",
      rating: 4,
    },
    {
      id: 15,
      category: "Breakfast",
      name: "Fig and Raisins Oatmeal",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu34.jpg",
      rating: 5,
    },
    {
      id: 16,
      category: "Dessert",
      name: "Silky Smooth Panacotta",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu35.jpg",
      rating: 5,
    },
    {
      id: 17,
      category: "Dessert",
      name: "Triple Decker Cranberry Cake",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu36.jpg",
      rating: 4,
    },
    {
      id: 18,
      category: "Dessert",
      name: "Very Berry Healthy Summer Smoothie",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu37.jpg",
      rating: 5,
    },
    {
      id: 19,
      category: "Desert",
      name: "Crispy Orange Chips",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu38.jpg",
      rating: 5,
    },
    {
      id: 20,
      category: "Dessert",
      name: "Tumeric Lavender Tea",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu39.jpg",
      rating: 5,
    },
    {
      id: 21,
      category: "Dessert",
      name: "Blue Velvet Brownies",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu40.jpg",
      rating: 4,
    },
    {
      id: 22,
      category: "Dessert",
      name: "Birthday Cupcakes",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu41.jpg",
      rating: 5,
    },
    {
      id: 23,
      category: "Meal",
      name: "Gourmet Fillet in Roasted Almond Sauce",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu42.jpg",
      rating: 4,
    },
    {
      id: 24,
      category: "Dessert",
      name: "Four Ingredient Oatmeal Pancakes",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu43.jpg",
      rating: 5,
    },
    {
      id: 25,
      category: "Meal",
      name: "Spinach and Cheese Pasta",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu2.jpg",
      rating: 5,
    },
    {
      id: 26,
      category: "Dessert",
      name: "Fancy Glazed Dounts",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu3.jpg",
      rating: 4,
    },
    {
      id: 27,
      category: "Meal",
      name: "Mighty Cheesy Breakfast Burger",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu4.jpg",
      rating: 5,
    },
    {
      id: 28,
      category: "Dessert",
      name: "Berry Maddness Biscuts",
      img: "https://fabrx.co/fullpreview/tastebite/assets/images/menus/menu7.jpg",
      rating: 5,
    }
  ];
  
  export default recipes;
  